import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import animal from "../lib/animal.json";
import adjetivo from "../lib/adjetivo.json";
import verbo from "../lib/verbo.json";
import adverbios from "../lib/adverbios.json";
import { useState } from "react";
import getScreenshot from "../services/carbonController";

export default function Home() {
  const [ditado, setDitado] = useState("");

  const handleChange = () => {
    const randomAnimal = animal[Math.floor(Math.random() * animal.length)];
    const randomAdjetivo =
      adjetivo[Math.floor(Math.random() * adjetivo.length)];
    const randomVerbo = verbo[Math.floor(Math.random() * verbo.length)];
    const randomAdverbios =
      adverbios[Math.floor(Math.random() * adverbios.length)];

    setDitado(
      `${randomAnimal} ${randomAdjetivo} não ${randomVerbo} ${randomAdverbios}`
    );
    getScreenshot({
      f: `${randomAnimal} ${randomAdjetivo} não ${randomVerbo} ${randomAdverbios}`,
      t: "light",
      o: "./output",
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Gerador de ditos populares</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Gerador de ditos <a>Populares!</a>
        </h1>

        <button onClick={handleChange} className={styles.card}>
          <h3>Gerar &rarr;</h3>
        </button>

        <div style={{ alignItems: "center", borderWidth: 0.3 }}>
          <h2>{ditado}</h2>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
